### ISSUE TITLE
Error during uploading apk

### ISSUE THREAD

**Issue by jekakm** [jenkinsci/fabric-beta-publisher-plugin#24]
I'm got this error while try to upload apk to fabric beta

`Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:667)
	at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /var/lib/jenkins/workspace/new_cookorama-android/app/build/outputs/apk/app-release.apk
	at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:64)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
	... 2 more`

**Comment by egor-n** [comment]
Seems like the `crashlytics-build.properties` is not present in your APK. Did you add and apply Crashlytics Gradle plugin to the project?

**Comment by jekakm** [comment]
yeah, my fault, sorry

**Comment by RomanBalata** [comment]
Hi, I have the same error, how to fix this?
