### ISSUE TITLE
Some relationship with Android sdk version 27

### ISSUE THREAD

**Issue by hyunjutrudylee** [jenkinsci/fabric-beta-publisher-plugin#27]
Recently, our team upgraded compileSdkVersion from 25 to 27, 
and this continuously cause Fabric-beta-publisher-plugin fails to upload apk to Beta, Fabric.

Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:667)
	at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it can't find the specified file: /home/ubuntu/.jenkins/workspace/*****.apk
	at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:51)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
	... 2 more

Even now, the other branch of the project which has 25 compileSdkVersion works totally fine with Fabric-beta-publisher-plugin. Have any idea for this error?

Specifically, we changed build.gradle like below.

classpath 'com.android.tools.build:gradle:2.3.3' -> '3.0.1'
compileSdkVersion = 25 -> 27
buildToolsVersion = '25.0.3' -> 27.0.3
supportLibraryVersion = '25.4.0' -> 27.0.2

**Comment by hyunjutrudylee** [comment]
self-solved!

apk folder path slightly changed by sdk 27, so anyone is faced with this error should change apk folder path in Jenkins. Thank you!
