### ISSUE TITLE
SocketTimeoutException

### ISSUE THREAD

**Issue by FRizzonelli** [jenkinsci/fabric-beta-publisher-plugin#9]
Hello,

your plugin is awesome, it makes really simple to deploy to Fabric from Jenkins.

All was setted up correctly, i was able to deploy to Fabric Beta and everything was working.
Than after some days, the plugin stopped working with the following output.

`Fabric Beta Publisher Plugin:
ERROR: Step ‘Upload .apk to Fabric Beta’ aborted due to exception: 
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
Caused: java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:212)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:288)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:242)
	at okio.RealBufferedSource.read(RealBufferedSource.java:45)
	at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:381)
	at okio.RealBufferedSource.read(RealBufferedSource.java:45)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at retrofit2.OkHttpCall$ExceptionCatchingRequestBody$1.read(OkHttpCall.java:279)
	at okio.RealBufferedSource.readAll(RealBufferedSource.java:162)
	at retrofit2.Utils.buffer(Utils.java:303)
	at retrofit2.BuiltInConverters$BufferingResponseBodyConverter.convert(BuiltInConverters.java:99)
	at retrofit2.BuiltInConverters$BufferingResponseBodyConverter.convert(BuiltInConverters.java:92)
	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at fabric.beta.publisher.FileUtils.downloadCrashlyticsTools(FileUtils.java:31)
	at fabric.beta.publisher.FabricBetaPublisher.prepareCrashlytics(FabricBetaPublisher.java:119)
	at fabric.beta.publisher.FabricBetaPublisher.perform(FabricBetaPublisher.java:71)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Finished: FAILURE`

Any idea why am I receiving this error?

Best regards!

Fabrizio

**Comment by egor-n** [comment]
Here's the faulty line in the stacktrace:

> at fabric.beta.publisher.FileUtils.downloadCrashlyticsTools(FileUtils.java:31)

This plugin uses the Crashlytics Tools jar which is downloaded from [here](https://ssl-download-crashlytics-com.s3.amazonaws.com/android/ant/crashlytics.zip). As you can see it is hosted on the S3 which was down [a couple of days ago](https://aws.amazon.com/message/41926/) – this is the reason the plugin could not download it.

The S3 works fine right now so you shouldn't be seeing this issue anymore.

**Comment by dmitrikudrenko** [comment]
Still see the error
```
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:576)
	at okhttp3.internal.Platform.connectSocket(Platform.java:121)
	at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:185)
	at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:170)
	at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
	at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187)
	at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123)
	at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93)
	at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296)
	at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
	at okhttp3.RealCall.getResponse(RealCall.java:243)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at fabric.beta.publisher.FileUtils.downloadCrashlyticsTools(FileUtils.java:31)
	at fabric.beta.publisher.FabricBetaPublisher.prepareCrashlytics(FabricBetaPublisher.java:119)
	at fabric.beta.publisher.FabricBetaPublisher.perform(FabricBetaPublisher.java:71)
```

**Comment by michaldrabik** [comment]
Also getting this error quite often:
```
Fabric Beta Publisher Plugin:
ERROR: Step ‘Upload .apk to Fabric Beta’ aborted due to exception: 
java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:212)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:288)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:242)
	at okio.RealBufferedSource.read(RealBufferedSource.java:45)
	at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:381)
	at okio.RealBufferedSource.read(RealBufferedSource.java:45)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at retrofit2.OkHttpCall$ExceptionCatchingRequestBody$1.read(OkHttpCall.java:279)
	at okio.RealBufferedSource.readAll(RealBufferedSource.java:162)
	at retrofit2.Utils.buffer(Utils.java:303)
	at retrofit2.BuiltInConverters$BufferingResponseBodyConverter.convert(BuiltInConverters.java:99)
	at retrofit2.BuiltInConverters$BufferingResponseBodyConverter.convert(BuiltInConverters.java:92)
	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at fabric.beta.publisher.FileUtils.downloadCrashlyticsTools(FileUtils.java:31)
	at fabric.beta.publisher.FabricBetaPublisher.prepareCrashlytics(FabricBetaPublisher.java:119)
	at fabric.beta.publisher.FabricBetaPublisher.perform(FabricBetaPublisher.java:71)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
	... 24 more
Finished: FAILURE
```
